### ISSUE TITLE
adding the reference to the .taxon

### ISSUE THREAD

**Issue by myrmoteras** [CatalogueOfLife/checklistbank#1096]
It seems that the reference is missing. 

https://www.checklistbank.org/dataset/138562/taxon/0CF2621593C45BDA86AE45DE3C908ADD.taxon

![image](https://user-images.githubusercontent.com/4609956/188743181-e468aabc-c48b-405a-af07-2a38a6be4ce4.png)

![image](https://user-images.githubusercontent.com/4609956/188743502-30054327-d322-4278-863c-83986e44a340.png)

however, the reference is provided in the DWCA in references.txt in the "full_reference", eg  `Rajeeshkumar, Meleppura, Pietsch, Theodore W., Saravanane, Naryanane (2022): A new species of deep-sea anglerfish, genus Himantolophus (Lophiiformes: Himantolophidae) from the Andaman Sea, India. Zootaxa 5178 (6), 589-594: 590-590, DOI:https://doi.org/10.11646/zootaxa.5178.6.6`

or part is provided in metadata.json 

`"source": [
		{
			"author": [
				{
					"given": "Meleppura",
					"family": "Rajeeshkumar"
				},
				{
					"given": "Theodore W.",
					"family": "Pietsch"
				},
				{
					"given": "Naryanane",
					"family": "Saravanane"
				}
			],
			"type": "article-journal",
			"containerTitle": "Zootaxa",
			"volume": "5178",
			"issue": "6",
			"page": "589-594",
			"issued": "2022-08-31",
			"doi": "10.11646/zootaxa.5178.6.6",
			"id": "10.11646/zootaxa.5178.6.6",
			"title": "A new species of deep-sea anglerfish, genus Himantolophus (Lophiiformes: Himantolophidae) from the Andaman Sea, India"`

**Comment by mdoering** [comment]
I have added support for the EOL reference extension, so the reference shows up now in the taxon page:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/327505/188867428-24151528-2129-4ba5-8952-8a7c1e0a4cd0.png">

The bad one with just the authors is still there though. This is because you have populated the dc:source field of the [multimedia extension](https://rs.gbif.org/extension/gbif/1.0/multimedia.xml) with just the auhors. So either put the entire citation into there or just remove it alltogether?

**Comment by mdoering** [comment]
note also that both the DOI and URI are missing from the EOL reference data:
https://www.checklistbank.org/dataset/138562/verbatim/5
