### ISSUE TITLE
CLB name match issues

### ISSUE THREAD

**Issue by chantalhuijbers** [CatalogueOfLife/checklistbank#1131]
When using the CLB name match tool, it matches incorrect names against accepted names.

E.g. the following names are all matched against Pinus pinea L. (accepted). This is incorrect as Pinus pinea, Dario is not an existing name.

Input data:
scientificName,author
Pinus pinea,
Pinus pinea L.,
Pinus pinea,L.,
Pinus pinea, Dario
Pinus pinea Dario,

Result:
![image](https://user-images.githubusercontent.com/71767106/201110152-8077c687-8f8f-4b75-a7a8-95c8a02c2b20.png)

**Comment by mdoering** [comment]
@thomasstjerne not sure how to handle this in the UI.
At least for all canonical index matches we should provide a (downloadable) warning?

http://api.checklistbank.org/name/matching?q=Pinus%20pinnea%20LDario

When queried already with a canonical name the match type is exact (or fuzzy), but not canonical. So that should catch only the problem cases:
http://api.checklistbank.org/name/matching?q=Pinus%20pinnea

**Comment by sharifX** [comment]
One suggestion could be to use the _"type": "canonical"_ response from the API as a flag to highlight only the canonical part of the name in the UI result page. This highlight could either be bold or a different colour -- but you need to think about web accessibility issues as well. 

But the status "accepted" is still misleading here.

**Comment by mdoering** [comment]
Good idea, Though this then needs to be different in the downloadable CSV.

The status column simply is the taxonomic status as applied by the target dataset. Thats perfectly correct, but agree we might need to communicate that better. @thomasstjerne maybe use a slightly grey/colored background for all target dataset columns?
