### ISSUE TITLE
Imports page wrong on reload

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1156]
Sth is odd with the imports page. When I come to it first time or click through in the menu its perfectly fine. But reloading the page wrongly places historical imports as running imports and does not show the real running ones.

First visit:
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/327505/212048153-a5b22ffd-87e2-4fa8-a2b9-1d225189eddc.png">

After a page reload:
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/327505/212048258-2d7dace4-04c7-46c7-8df4-f0967a559311.png">

**Comment by gdower** [comment]
To reproduce:

1) Navigate to here: https://www.checklistbank.org/imports
2) The import queues will load correctly
3) View the URL after it loads and it will be: https://www.checklistbank.org/imports?limit=10&offset=0&state=unchanged&state=finished&state=canceled&state=failed
4) Hit the refresh button and it loads the finished datasets into the running queue because of the URL state params affect the running queue:

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/8573609/219091251-fbe48896-aa36-4af3-bf36-75b915ba4b68.png">

Ideally if you can prevent the state parameters from loading into the URL, it will fix the issue.

**Comment by gdower** [comment]
Or maybe only target the URL params at the finished queue? It might be useful to still be able to filter the finished queue by state.
