### ISSUE TITLE
Setting a root taxon for a download returns a 404 error.

### ISSUE THREAD

**Issue by Sherrin-ALA** [CatalogueOfLife/checklistbank#1290]
When I attempt to select a root taxon on the download page for this checklist - https://www.checklistbank.org/dataset/53879/download - the page flips to display a 404 error.

Step to reproduce:
On the download page, type Animalia into the "Choose root taxon (optional)" checkbox
Select "Animalia (kingdom)" from the suggested list
Page refreshes and displays 404 error.

**Comment by mdoering** [comment]
The UI calls this API resource:
https://api.checklistbank.org/dataset/53879/taxon/https://biodiversity.org.au/afd/taxa/4647863b-760d-4b59-aaa1-502c8cdf8d3c

The problem is that the identifier is a URL itself and needs to be url encoded like this:
https://api.checklistbank.org/dataset/53879/taxon/https%3A%2F%2Fbiodiversity.org.au%2Fafd%2Ftaxa%2F4647863b-760d-4b59-aaa1-502c8cdf8d3c
