### ISSUE TITLE
Why I am not able to flag 149 accepted names as Provisionally Accepted in the World Plants?

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1437]
### Description

I am trying to change name status to Provisionally Accepted with these 149 names in World Plants:

https://www.checklistbank.org/catalogue/3/dataset/1141/workbench?decisionMode=_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=500&nomstatus=manuscript&offset=0&status=accepted

With the first attempt,  CLB reported successful completion of the decision process. However, names have no decision after I refreshed window in the browser.

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/b4151bb4-cad6-43dd-a480-ddef2417e1b5)

With the second attempt to repeat decision for these 149 names, CLB reported error 400:

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/778fef49-4552-436e-9a80-045fe4c441f5)

After another refresh, still there are no decisions:

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/aec6a9b0-350e-4475-bb58-775622dcc77a)

Would it be possible to fix this bug, which was reported with AC23, but still exists? 

### What browsers are you seeing the problem on?

Mozilla FireFox latest

**Comment by mdoering** [comment]
The search correctly is not cached, that's not the reason. And decisions do exist. Some of them, e.g. Acanthophyllum gharehbilensis, already exist since September 2023: https://www.checklistbank.org/catalogue/3/decision?limit=100&name=Acanthophyllum&offset=0&subjectDatasetKey=1141

I suspect the search index is missing these decisions, rebuiliding it now for world plants.

**Comment by mdoering** [comment]
works again
