### ISSUE TITLE
Checklistbank: I am not able open GLI & WOL in the project

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1444]
### Description

While inside the CoL3 project, I can no longer open _some_ source GSDs anymore for unknown reasons. So far, I met problem with GLI & WOL (whereas other GSDs, such as ITIS, Entiminae, Scarabs, WCO are accessable as expected). 
https://www.checklistbank.org/catalogue/3/metadata

_Steps:_  COL - Source - Select, typed "GLI" or "WOL" in a search box. Drop list is empty, and these GSDs are unavailable: 

![image](https://github.com/user-attachments/assets/0a5f21a5-714c-494b-92c2-9064051ad8d8)

![image](https://github.com/user-attachments/assets/bdf33a6c-033d-4ce1-a770-8fa4a271983c)

The problem was met first time on 2024-07-17 and repeated on 2024-07-18

### What browsers are you seeing the problem on?

Firefox

### ChecklistBank URL

https://www.checklistbank.org/catalogue/3/metadata

**Comment by mdoering** [comment]
@thomasstjerne this seems to be a limit of the max numbers of sources being loaded into the UI - I don't see any search/suggest to the API going on. With Plazi there are now >50k source datasets, so loading these all into the client memory is not feasable.

We could restrict the sources to non merge source only. But better would be a more dynamic interaction with the API to search for matches rather than keeping them all in memory. I do fear though the memory list of sources is used in other places as well?

**Comment by mdoering** [comment]
https://api.checklistbank.org/dataset?contributesTo=3&limit=1000 is being called.
@thomasstjerne Shall I develop some suggest/search method that is quick to call?

**Comment by mdoering** [comment]
>I will expose this method on prod tomorrow:
yes, I am deploying the fix that uses the query right now

**Comment by mdoering** [comment]
works now: https://api.checklistbank.org/dataset/3/source/suggest?q=fish
