### ISSUE TITLE
CLB: I cannot access WOL from inside CoL project-3

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1455]
### Description

I am not able to access WOL from inside CoL project-3 at https://www.checklistbank.org/catalogue/3/metadata
 
_Select Source_ is empty for WOL (id 125101):

![image](https://github.com/user-attachments/assets/47015dd2-59c9-4db7-9226-b4852cc9e080)

### What browsers are you seeing the problem on?

Firefox

### ChecklistBank URL

https://www.checklistbank.org/catalogue/3/metadata

**Comment by mdoering** [comment]
@thomasstjerne the UI does not use a search but instead seems to load all source datasets into the client:
> https://api.checklistbank.org/dataset?contributesTo=3&limit=1000

Because we now have many plazi sources the first 1000 does not cover all sources.
It would be best to do a regular search to select the source:

> https://api.checklistbank.org/dataset?contributesTo=3&q=WOL

Even better, because its faster returning stripped down dataset instances would be to use:
> https://api.checklistbank.org/dataset/3/source/suggest?merge=false&q=WOL

**Comment by mdoering** [comment]
@thomasstjerne the source suggest had a bug ignoring the query string which I just fixed. Will be deployed shortly. 
Please use that resource for the source selection, not the full dataset one.
