### ISSUE TITLE
Bug: faulty sync in 3i Auchenorrhyncha

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1488]
### Description

I have synced 3i Auchenorrhyncha on 2024-10-31. Seems, sync failed, because its duration lasted for a few seconds and results were incorrect. However, the report says "Syncs completed:

![image](https://github.com/user-attachments/assets/8aeddfda-b532-4c02-8478-3ace14dd6527)

### What browsers are you seeing the problem on?

Firefox

### ChecklistBank URL

https://www.checklistbank.org/catalogue/3/assembly?assemblyTaxonKey=ZaRXXSGsDIsJ6Kew5IDLj&datasetKey=2317&sourceTaxonKey=48812

**Comment by mdoering** [comment]
Only 585 taxa have been synced. I suspect this is due to blocking decisions which there are thousands of in this dataset?
E.g. infraorder 
[Fulgoromorpha](https://www.checklistbank.org/catalogue/3/dataset/2317/taxon/56032), superfamily 
[Cercopoidea](https://www.checklistbank.org/catalogue/3/dataset/2317/taxon/321), subfamily 
[Endoiastinae](https://www.checklistbank.org/catalogue/3/dataset/2317/taxon/51803) ?

But parvorder Clypeata is not coied even though there is no decision. That's not right.

**Comment by mdoering** [comment]
I have setup a [sector on dev](https://www.dev.checklistbank.org/catalogue/274650/assembly?datasetKey=2317) and only blocked the Fulgoromorpha. It sync 88888 names. So it is likely some decisions on prod that cause the issue?

**Comment by yroskov** [comment]
Parvorder Clypeata unlikely creates problem. It was there in the past: https://www.catalogueoflife.org/?taxonKey=C69Q7

3 nodes should be blocked: 
[Fulgoromorpha](https://www.checklistbank.org/catalogue/3/dataset/2317/taxon/56032), superfamily - data from FLOW
[Cercopoidea](https://www.checklistbank.org/catalogue/3/dataset/2317/taxon/321), subfamily - data from COOL
[Endoiastinae](https://www.checklistbank.org/catalogue/3/dataset/2317/taxon/51803), empty duplicated entry

**Comment by yroskov** [comment]
@mdoering, can one of two my steps in 3i Auchenorrhyncha caused the problem?

(1) 2024-10-25: "block" decision in the family Membracidae was cancelled 
(2) 2024-10-31: infraorder Fulgoromorpha was moved in _Assembly - Modify Tree_ from outside suborder Auchenorrhyncha inside it

**Comment by mdoering** [comment]
Not that I can think of. I am replaying your setup on dev now where I can better debug syncs

**Comment by mdoering** [comment]
It was indeed a code problem with merge sectors that come from the same source:

<img width="1149" alt="image" src="https://github.com/user-attachments/assets/9ad7ab05-b487-40a7-b53a-f2ae54db110b">

@camiplata  added 3 merge sectors to include the 3i data which was excluded in the main release due to the use of other sources.
All subjects from sectors of the same source are automatically blocked, so they do not appear twice. But for merge sectors this does not make sense and hence Clypeata and Fulgoroidea was entirely blocked. I have change to code to only block non merge sector subjects now, gonna deploy that later today!
