### ISSUE TITLE
Reference issues should point to references search, not names search

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#312]
On the issues page, issues like "Unmatched Reference Brackets" should point to references search, not names search. Currently the "Unmatched Reference Brackets" issue [links to names search with no matches](https://www.col.plus/dataset/1008/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=unmatched%20reference%20brackets&limit=100). It doesn't [look like reference search has the capability right now](https://www.col.plus/dataset/1008/reference?facet=issue&issue=unmatched%20reference%20brackets&limit=50&limit=100&offset=0), so this might need search and API enhancements. 

We could potentially use the issues page like a review queue when we are working with GSDs on updates, which would be a way to get [these typos](https://github.com/Sp2000/colplus-repo/issues/41) fixed in the source data.

**Comment by mdoering** [comment]
backend issue multivalue parameter added, yet to be deployed

**Comment by thomasstjerne** [comment]
@gdower since this issue was originally created, we have added the links to the verbatim browser that takes you directly to the affected lines in the data. It is not really feasible to distinguish where the link in the right column goes. Maybe I should remove the name search link entirely and only have the verbatim links as these are much more useful to debug data issues?

**Comment by mdoering** [comment]
That sounds fine to me, all details are only present on the verbatim pages and these take you back to taxon or (upcoming reference) pages anyways.

Note also that the `Unmatched Reference Brackets` issue can link to both Reference and Name records, which can also have a verbatim `publishedIn` property.
