### ISSUE TITLE
Taxonomic Coverage in ITIS is not available in the preview

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#809]
Pointing ITIS sectors in CoL to @DaveNicolson, I have spotted that Taxonomic Coverage is not available at https://preview.catalogueoflife.org/data/dataset/2144:

![image](https://user-images.githubusercontent.com/28574252/108771097-c6399d80-7520-11eb-87f1-1222119d64c7.png)

For attention of @mdoering @thomasstjerne

**Comment by thomasstjerne** [comment]
There is a sector 109217 where the subject has only an ID, no rank or name.
I have adjusted the frontend to just skip this for the taxonomic coverage, but it may worth looking into why the rank and name is missing:

````
created: "2020-08-25T21:00:51.89555"
createdBy: 102
datasetKey: 2261
id: 867
mode: "attach"
modified: "2021-01-27T17:01:41.988956"
modifiedBy: 103
originalSubjectId: "109217"
size: 0
subject: {id: "109217", broken: false}
subjectDatasetKey: 2144
syncAttempt: 10
target: {id: "C2L", name: "Coleoptera", rank: "order", broken: false}
````

**Comment by mdoering** [comment]
Thanks Thomas. @gdower this is likely the rematching problem we discovered some weeks ago.

**Comment by DaveNicolson** [comment]
I see 109217 in there, and on checking ITIS I see this TSN is a direct child of Coleoptera in ITIS. It is Suborder Archostemata, the only suborder in the COL Insecta (from a quick check). I don't know why this one suborder is included, but not the others, but I have to wonder if the rank of suborder is triggering the issue here. It looks very odd in https://preview.catalogueoflife.org/ the way it is now...
