### ISSUE TITLE
Please change menu item "About" back to "Metadata"

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#868]
Frontend version: a65157e May 12, 2021 10:02 AMBackend version: 3e495b2 May 12, 2021 1:46 PM

Please change menu item "About" back to "Metadata"

@thomasstjerne

**Comment by mdoering** [comment]
Do you think metadata is more intuitive for users? For editing forms I agree this makes more sense. But for a landing / homepage of a dataset that DOIs link to and which combine more overview information? Maybe `Overview` is not a bad choice. I am not sure if _metadata_ is a good title for the source pages in the portal that add basic statistics: https://www.catalogueoflife.org/data/dataset/2144

I am really 50:50 on this one. Happy to revert to metadata, but let's briefly think about all options. Just because we are used to metadata and links went out to data providers is a bit weak.

Maybe it makes sense to differ between the metadata (patch) forms and the public _overview_ pages which also add metrics and taxonomic coverage?

Please also see https://github.com/CatalogueOfLife/checklistbank/issues/860

**Comment by mdoering** [comment]
@thomasstjerne if we change back to metadata I would prefer to also use `metadata` in the path, not just `meta` as we did before.
