### ISSUE TITLE
Add pure metadata editor

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#940]
Allow metadata to be edited and then downloaded as YAML without storing it in any real dataset.
Ideally a user can prepopulate the editor by a) uploading an existing YAML or b) by selecting an existing dataset (key).

**Comment by mdoering** [comment]
I will update the validator to return a YAML when a yaml Accept header is present.

**Comment by gdower** [comment]
If possible, it would be useful if we could reference this tool by URL pre-populated with metadata with a URL like:

https://data.catalogueoflife.org/tools/metadata-generator/1027

At least in Google Chrome, the yaml file renders in the browser instead of downloading, and users are getting confused by what they're supposed to do with the output. Ideally if we can configure Apache to send the yaml file as a download, that would be preferable. Maybe this would work?

```
AddType application/octect-stream .yaml
AddType application/octect-stream .yml
```

**Comment by mdoering** [comment]
I have changed the metadata parser to return JSON, YAML or EML if requested via the Accept header - or using the respective file suffix that will set the header without the need to mess with http headers:

> curl -s -H "Content-Type: application/json" -H "Accept: application/x-yaml" --data-binary @1010.json -X POST "http://api.catalogueoflife.org/parser/metadata?format=YAML"

**Comment by thomasstjerne** [comment]
https://data.dev.catalogueoflife.org/tools/metadata-generator
The tool can be given a template like this https://data.dev.catalogueoflife.org/tools/metadata-generator?template=2182
