### ISSUE TITLE
Missing CoL name status in synonymy on species details page

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#957]
For attention of @mdoering & @thomasstjerne 

There is no indication of CoL name statuses in a list of synonyms on Species Details page. Statuses used in the database: synonym, ambiguous synonym, misapplied name. 

For example, Trifolium johnstonii sensu Edwards Edwards & Bogdan is fllaged in the database as "misapplied name", but there is no such information on the page:
https://www.catalogueoflife.org/data/taxon/58Q6G

![image](https://user-images.githubusercontent.com/28574252/138334915-34b8c17f-808f-4420-9178-15b2f7642123.png)

Note: these statuses displayed in the Search, but it's not enough.

![image](https://user-images.githubusercontent.com/28574252/138335376-f0e20ec1-1f73-45cf-9100-3eec0685dc5f.png)

**Comment by mdoering** [comment]
See also user feedback at https://github.com/CatalogueOfLife/data/issues/406

**Comment by mdoering** [comment]
The nomenclatural status is also oddly represented in the synonymy:
https://www.checklistbank.org/dataset/3LR/taxon/8LVYQ

<img width="753" alt="image" src="https://user-images.githubusercontent.com/327505/160107702-36448086-b2d8-44b0-b8a8-6475545c8478.png">

**Comment by mdoering** [comment]
We should use the nomenclatural code of the synonym or if missing from the taxon to determine the correct terminology by the code for the nomstatus: http://api.checklistbank.org/vocab/nomstatus

We could also show the abbreviation. Showing our own code agnostic value is probably not ideal for the UI

**Comment by mdoering** [comment]
We definitely need a dedicated synonyms page that exposes all information about a synonym. It should be very visible that this is not a taxon page, but the following information is shared across all name usages, regardless if accepted or not:

 - ID & origin (only show origin if other than `source`)
 - status
 - name
 - names index link 
 - external link
 - remarks 
 - accordingTo with link to reference page via accordingToID
 - name relations
 - type material

**Comment by thomasstjerne** [comment]
> The nomenclatural status is also oddly represented in the synonymy: https://www.checklistbank.org/dataset/3LR/taxon/8LVYQ

It looks like the nomenclatural status is in the `labelHtml` here: https://api.checklistbank.org/dataset/3LR/taxon/8LVYQ/info
The UI translates the code agnostic `nomStatus` into a code specific one from https://api.catalogueoflife.org/vocab/nomstatus (defaulting to zoological)

If the nomStatus is in the `labelHtml`, this gives a "double" representation in the UI

**Comment by mdoering** [comment]
Indeed. I can easily remove it from the label, but I fear it is important in other places like the workbench or duplicate UI.
It also seems the UI does not translate the status:

`Abax marginalis Letzner, 1852 unavailable name` comes from the labelHtml, `(not established)` is appended by the UI


Here is an **IRMNG** synonym with the nomstatus given, but not included in the authorship or label:
https://api.checklistbank.org/dataset/2007/nameusage/urn%3Alsid%3Airmng.org%3Ataxname%3A1275869

The UI then appends the generic status (not the zoological one) in brackets:
https://www.checklistbank.org/dataset/2007/taxon/urn%3Alsid%3Airmng.org%3Ataxname%3A1034966
https://www.checklistbank.org/dataset/2007/name/urn%3Alsid%3Airmng.org%3Ataxname%3A1275869


Here is a World Plants manuscript example `Aeonium millennium (O. Arango) comb. ined.`:
https://www.checklistbank.org/dataset/1141/taxon/Saxifragales-Crassulaceae-Sempervivoideae-Aeonium-millennium-(O.%20Arango)
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/327505/160803402-b042e1ad-542b-4a53-8ca7-1aab58305ec2.png">

The `comb.ined.` part is produced by the API and added to the label, the UI does not add anything:
https://api.checklistbank.org/dataset/1141/taxon/Saxifragales-Crassulaceae-Sempervivoideae-Aeonium-millennium-(O.%20Arango)


The problem comes with the nom status given explicitly, as part of the authorship or even the publication:

```
ID	rank	scientificName	authorship	publishedIn	status
1	species	Abies alba	(Aiton) Michx., Fl. Bor.-Amer. (Michaux) 2: 207 (1803), nom. illeg.		
2	species	Abies alba	(Aiton) Michx.	Fl. Bor.-Amer. (Michaux) 2: 207 (1803)	nom. illeg.
3	species	Abies alba	(Aiton) Michx., nom. illeg.	Fl. Bor.-Amer. (Michaux) 2: 207 (1803)	
4	species	Abies alba	(Aiton) Michx., nom. illeg.	Fl. Bor.-Amer. (Michaux) 2: 207 (1803)	nom. illeg.
```

The importer should interpret that ideally as the same. But when we have a nom.illeg. status extracted should it still be present in the authorship and publication? I have tried to code for removing it, as it would otherwise duplicate things and create inconsistent names/labels.

**Comment by mdoering** [comment]
The above examples currently ends up as:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/327505/160823321-4f66ba14-3660-4620-ad39-3f77f91fa08b.png">

**Comment by mdoering** [comment]
I tend to think the label should not include the nom status

**Comment by mdoering** [comment]
Moved creating synonym pages to its own issue: https://github.com/CatalogueOfLife/checklistbank/issues/1034
